### ISSUE TITLE
FYI: girosolution ends service

### ISSUE THREAD

**Issue by Hertel84** [extcode/cart_girosolution#10]
Sehr geehrte Damen und Herren,

herzlichen Dank für Ihr Interesse an unseren Zahlungsdienstleistungen. Leider können wir Ihnen keinen Vertrag mehr anbieten.

Das hat Gründe: Die S-Public Services GmbH wird sich stärker auf ihre Aufgaben als Dienstleister für Bund, Länder und Kommunen konzentrieren. **Deshalb ziehen wir uns auch aus dem Markt für Zahlungsdienstleistungen für den E-Commerce (Online-Handel) und webbasierte Bezahlverfahren für Einzelunternehmen und private Rechtsformen zurück.**

Wenn Sie Zahlungsdienstleistungen für Ihren Online-Shop oder technische Verfahren wie den Payment-Link oder Kreditkarte Mail-/Telephone-Order wünschen, wenden Sie sich bitte an den Firmenkundenbetreuer Ihrer Sparkasse oder an die **Payone GmbH**. Dort bekommen Sie alle Leistungen, die wir Ihnen bisher angeboten haben: https://www.payone.com/

Wir wünschen Ihnen persönlich und für Ihr Unternehmen alles Gute für die Zukunft!

**Comment by extcode** [comment]
Vielen Dank für die Nachricht. Ich sehe hier aktuell kein Punkt, an dem gehandelt werden müsste. Eventuell könnte ich das in die Dokumentation aufnehmen.

Es gibt aber mindestens eine Verwendung in Kommunaler Trägerschaft, die GiroSolution für die Abwicklung im Onlinehandel verwenden. Ich werde die Nachricht entsprechend weiterleiten und erfragen, ob dort eine entsprechende E-Mail ebenfalls eingegangen ist.

Kann das Ticket geschlossen werden?
